config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('store.urls', namespace='store')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('cart/', views.cart_list, name='cart_list'),
    path('cart/add/<int:product_id>/', views.cart_add,
         name='cart_add'),
    path('cart/remove/<int:cart_id>/', views.cart_remove,
         name='cart_remove'),
    path('order/create/', views.order_create, name='order_create'),

]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [

    path('', views.product_list, name='product_list'),

    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),

    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),

]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from store.models import Product

User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='carts')
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='carts')
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                default=0)
    duration = models.PositiveSmallIntegerField(default=1)

    objects = models.Manager()

    def __str__(self):
        return f'{self.user} {self.product}'

    def save(self, *args, **kwargs):
        if self.price == 0:
            self.price = self.product.price * self.duration

        super().save(*args, **kwargs)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='orders')
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.__class__.__name__}: {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE,
                              related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name="order_items")
    price = models.DecimalField(max_digits=10, decimal_places=2)

    duration = models.PositiveSmallIntegerField(default=1)

    objects = models.Manager()

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price * self.duration

orders/forms.py
from django import forms

from orders.models import Order


class CartAddProductForm(forms.Form):
    duration = forms.TypedChoiceField(
        choices=[(i, str(i)) for i in range(1, 13)],
        coerce=int, widget=forms.Select(attrs={'class': 'form-select mb-2'}),
    )

    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'first_name',
            'last_name',
            'email',
            'address',
            'postal_code',
            'city',
            'state',
        )

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
        }

orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from store.models import Product
from .models import Cart, OrderItem
from .forms import CartAddProductForm, OrderCreateForm


@login_required
def cart_list(request):
    carts = Cart.objects.filter(user=request.user)
    form = CartAddProductForm()
    context = {
        'carts': carts,
        'form': form
    }

    return render(request,
                  'orders/cart/list.html',
                  context)


@require_POST
def cart_add(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart = Cart.objects.filter(user=request.user, product=product)
        if cart.exists():
            cart = cart.first()
            cart.duration = cd['duration']
            cart.price = cd['duration'] * cart.product.price
        else:
            cart = Cart(
                user=request.user,
                product=product,
                duration=cd['duration'],
            )
        cart.save()
        messages.success(request, 'Your cart has been added.')
    else:
        messages.error(request, "Invalid cart")
    return redirect('orders:cart_list')


@require_POST
def cart_remove(request, cart_id):
    cart = get_object_or_404(Cart, user=request.user, id=cart_id)
    cart.delete()
    messages.success(request, f'Your cart has been removed.')
    return redirect('orders:cart_list')


@login_required
def order_create(request):
    carts = request.user.carts.all()
    if request.method == 'POST':

        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for cart in carts:
                OrderItem.objects.create(
                    order=order,
                    product=cart.product,
                    price=cart.price,
                    duration=cart.duration,
                )
            messages.success(request, "Your order has been success")
            carts.delete()
            return redirect('payment:process')
        else:
            messages.error(request, "Something wrong with our informations!")
            return redirect('order:cart_list')
    else:
        form = OrderCreateForm()

    return render(request,
                  template_name='orders/order/create.html',
                  context={
                      'form': form,
                      'carts': carts
                  })

orders/templates/orders/cart/list.html
{% extends 'base.html' %}


{% block title %}
Cart
{% endblock title %}


{% block content %}
<div class="container">
    <table class="table align-item-center">
        <thead>
        <tr>
            <th scope="col">Image</th>
            <th scope="col">Product</th>
            <th scope="col">Duration</th>
            <th scope="col">Remove</th>
            <th scope="col">Price</th>
            <th scope="col">Total price</th>
        </tr>
        </thead>
        <tbody>
        {% for cart in carts %}
        <tr class="mt-5">
            <td>
                <img src="{{ cart.product.image.url }}" class="" style="width: 5rem; height: 5rem;" alt="">
            </td>
            <td class="mt-5">
                {{ cart.product.title }}
            </td>
            <td class="mt-5">
                <div class="d-flex justify-content-left">
                    <div >
                        {{ cart.duration }}-month
                    </div>
                    <div class="ms-5">
                        <form action="{% url 'order:cart_add' cart.product.id %}" method="post">
                    {% for field in form %}
                        {{ field }}
                    {% endfor %}
                    {% csrf_token %}
                    <button class="btn btn-info" type="submit">Update</button>
                </form>
                    </div>
                </div>

            </td>
            <td class="mt-5">
                <form action="{% url 'order:cart_remove' cart.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Remove</button>
                </form>
            </td>
            <td class="mt-5">${{ cart.product.price }}</td>
            <td class="mt-5">${{ cart.price }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex">
        <a href="{% url 'order:order_create' %}" class="btn btn-outline-primary">
            Checkout
        </a>
        <a href="{% url 'store:product_list' %}" class="btn btn-outline-dark ms-4">
            Go back
        </a>

    </div>
</div>
{% endblock content %}