config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('store.urls', namespace='store')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('cart/', views.cart_list, name='cart_list'),
    path('cart/add/<int:product_id>/', views.cart_add,
         name='cart_add'),
    path('cart/remove/<int:cart_id>/', views.cart_remove,
         name='cart_remove'),
    path('order/create/', views.order_create, name='order_create'),

]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [

    path('', views.product_list, name='product_list'),

    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),

    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),

]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [

    #
    path('password-change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # path("", include('django.contrib.auth.urls')),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),

    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update')


]

templates/components/.footer.html
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-5 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <svg class="bi" width="30" height="24">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 Company, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex fs-4">
            <li class="ms-3"><a class="text-body-secondary" href="#">
                <i class="fa-brands fa-telegram text-primary"></i>
            </a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#">
                <i class="fa-brands fa-instagram text-danger"></i>
            </a></li>
            <li class="ms-3"><a class="text-body-secondary" href="#">
                <i class="fa-brands fa-square-github text-dark"></i>
            </a></li>
        </ul>
    </footer>
</div>

templates/components/.header.html
{% load static %}
{% load order_tags %}




<nav class="">
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid container">

            <a class="navbar-brand text-light ms-5" href="{% url 'store:product_list' %}">
                Subscription
            </a>
            <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon "></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                    <li class="nav-item">
                        <a class="nav-link text-light" aria-current="page"

                           href="{% url 'store:product_list_by_category' 'Journal' %}">
                            Journals
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light"
                           href="{% url 'store:product_list_by_category' 'Newspaper' %}">
                            Newspapers
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light"
                           href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="#">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% get_total_price request.user as total_price %}
                    {% if request.user.is_authenticated %}

                    <li class="me-2 nav-item">
                        <div class="dropdown">
                            <a class="btn dropdown-toggle" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                {% if request.user.profile.image %}
                                <img src="{{ user.profile.image.url }}" class="rounded-circle shadow my-1"
                                     style="width: 2.3rem; height:2.3rem;" alt="">
                                {% else %}
                                <img src="{% static 'assets/unknown_user.jpg' %}" class="rounded-circle shadow my-1"
                                     style="width: 2.3rem; height:2.3rem;" alt="">
                                {% endif %}
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item text-center" href="#">
                                        Password change
                                    </a>
                                </li>
                                <li><a class="dropdown-item text-center" href="#">Something else here</a></li>
                                <li class="text-center">
                                    <form class="dropdown-item" action="{% url 'users:logout' %}">
                                        <input class="dropdown-item text-left" type="submit" value="Logout">
                                    </form>
                                </li>

                            </ul>
                        </div>

                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}" class="btn btn-outline-light ms-2">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:register' %}" class="btn btn-outline-light ms-2">Signup</a>
                    </li>
                    {% endif %}
                    <li class="nav-item ms-3 fs-6 mt-3 text-light"><a class="link-body-emphasis"
                                                                      href="{% url 'order:cart_list' %}">
                        <i class="fa-solid fa-cart-shopping text-light fs-4"></i>
                    </a> ($ {% if total_price %}
                        {{ total_price }}
                        {% else %}
                        0.00
                        {% endif %}
                        )
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid container">
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 "></ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-warning" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</nav>

templates/components/.messages.html
{% load static %}

<div class="container col-xxl-12 my-2">
    {% if messages %}
    <ul class="list-group">
        {% for message in messages %}
        <li
        {% if message.tags %} class="list-group-item shadow list-group-item-{{ message.tags }} fw-bolder fs-5 text-center"{% endif %}>
        {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>