config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('store.urls', namespace='store')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [

    path('', views.product_list, name='product_list'),

    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),

    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),

]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import stripe
from django.shortcuts import render, redirect, reverse
from decimal import Decimal
from django.conf import settings

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order = request.user.orders.last()

    if request.method == 'POST':
        success_url = request.build_absolute_uri(
            reverse('payment:completed')
        )
        cancel_url = request.build_absolute_uri(
            reverse('payment:canceled')
        )

        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }

        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.title,
                    },
                },
                'quantity': item.duration,
            })

        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())


def payment_completed(request):

    return render(request, 'payment/completed.html')


def payment_canceled(request):

    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends 'base.html' %}


{% block title %}
Payment canceled
{% endblock title %}


{% block content %}
<h1>Your payment has not been processed</h1>
<p>There was a problem processing your payment.</p>
{% endblock content %}

payment/templates/payment/completed.html
{% extends 'base.html' %}


{% block title %}
Payment success
{% endblock title %}


{% block content %}
<h1>Your payment was successful</h1>
<p>Your payment has been processed successfully.</p>
{% endblock content %}

payment/templates/payment/process.html
{% extends 'base.html' %}


{% block title %}
Cart
{% endblock title %}


{% block content %}
<div class="container">
    <table class="table align-item-center">
        <thead>
        <tr>
            <th scope="col">Image</th>
            <th scope="col">Product</th>
            <th scope="col">Duration</th>
            <th scope="col">Price</th>
            <th scope="col">Total price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
        <tr class="mt-5">
            <td>
                <img src="{{ item.product.image.url }}" class="" style="width: 5rem; height: 5rem;" alt="">
            </td>
            <td class="mt-5">
                {{ item.product.title }}
            </td>
            <td class="mt-5">
                <div class="d-flex justify-content-left">
                    <div>
                        {{ item.duration }}-month
                    </div>
                </div>

            </td>
            <td class="mt-5">${{ item.product.price }}</td>
            <td class="mt-5">${{ item.price }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <form action="{% url 'payment:process' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">
            Pay now
        </button>
    </form>
</div>
{% endblock content %}